# Generated by Django 5.1.2 on 2025-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numero',
            name='id',
        ),
        migrations.AddField(
            model_name='numero',
            name='numero_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
